### ISSUE TITLE
【Use】Use相关问题，无法安装

### ISSUE THREAD

**Issue by reov** [rao-pics/core#120]
![image](https://user-images.githubusercontent.com/47272954/229316337-f4f96ac5-19f5-4438-96c4-2e8ee62e1d76.png)
windows客户端一样无法使用
![image](https://user-images.githubusercontent.com/47272954/229316374-e9f4f26e-ed12-4631-9b9b-0a83c016659c.png)
![image](https://user-images.githubusercontent.com/47272954/229316561-4dea3aac-7354-410e-9808-98589f3f87d1.png)
部分时候能显示网页但是没有任何图片，页面都是空白

**Comment by meetqy** [comment]
@reov ![](https://user-images.githubusercontent.com/47272954/229316337-f4f96ac5-19f5-4438-96c4-2e8ee62e1d76.png) 这个应该是nsfw的依赖装不上，可以直接使用，把nsfw设置为false就行了，或者用 `cnpm i @raopics/plugin-nsfw`单独安装。

不开启nsfw
``` js
import raopics from '@raopics/use'

raopics({
 library: 'xx',
 plugin_nsfw: false
})
```

**Comment by reov** [comment]
不行，一样安装不了

**Comment by reov** [comment]
`     C:\Users\Tang\.cnpmrc
      or on the command line via: npm <command> --key value
      Config info can be viewed via: npm help config
\ [0/1] Installing seedrandom@^3.0.5
> @raopics/plugin-nsfw@1.2.2 › @tensorflow/tfjs-node@4.2.0 › @tensorflow/tfjs@4.2.0 › core-js@3 postinstall C:\WINDOWS\system32\node_modules\.store\core-js@3.29.1\node_modules\core-js
| [0/1] Installing seedrandom@^3.0.5
Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js:
> https://opencollective.com/core-js
> https://patreon.com/zloirock
> https://boosty.to/zloirock
> bitcoin: bc1qlea7544qtsmj2rayg0lthvza9fau63ux0fstcz

I highly recommend reading this: https://github.com/zloirock/core-js/blob/master/docs/2023-02-14-so-whats-next.md

> @raopics/plugin-nsfw@1.2.2 › @tensorflow/tfjs-node@4.2.0 › @tensorflow/tfjs@4.2.0 › core-js@3 postinstall, finished in 109ms
> @raopics/plugin-nsfw@1.2.2 › @tensorflow/tfjs-node@^4.2.0 install C:\WINDOWS\system32\node_modules\.store\@tensorflow+tfjs-node@4.2.0\node_modules\@tensorflow\tfjs-node
- [0/1] Installing seedrandom@^3.0.5
CPU-windows-4.2.0.zip
* Downloading libtensorflow
| [0/1] Installing seedrandom@^3.0.5
- [0/1] Installing seedrandom@^3.0.5
/ [0/1] Installing seedrandom@^3.0.5
node-pre-gyp install failed with error: Error: Command failed: node-pre-gyp install --fallback-to-build
node-pre-gyp http GET https://cdn.npmmirror.com/binaries/tf-builds/pre-built-binary/napi-v8/4.2.0/CPU-windows-4.2.0.zip
node-pre-gyp ERR! install response status 404 Not Found on https://cdn.npmmirror.com/binaries/tf-builds/pre-built-binary/napi-v8/4.2.0/CPU-windows-4.2.0.zip
node-pre-gyp WARN Pre-built binaries not installable for @tensorflow/tfjs-node@4.2.0 and node@18.15.0 (node-v108 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error response status 404 Not Found on https://cdn.npmmirror.com/binaries/tf-builds/pre-built-binary/napi-v8/4.2.0/CPU-windows-4.2.0.zip
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\Tang\AppData\Roaming\npm\node_modules\cnpm\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
gyp ERR! stack     at C:\Users\Tang\AppData\Roaming\npm\node_modules\cnpm\node_modules\node-gyp\lib\find-visualstudio.js:75:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\Tang\AppData\Roaming\npm\node_modules\cnpm\node_modules\node-gyp\lib\find-visualstudio.js:369:14)
gyp ERR! stack     at C:\Users\Tang\AppData\Roaming\npm\node_modules\cnpm\node_modules\node-gyp\lib\find-visualstudio.js:71:14
gyp ERR! stack     at C:\Users\Tang\AppData\Roaming\npm\node_modules\cnpm\node_modules\node-gyp\lib\find-visualstudio.js:390:16
gyp ERR! stack     at C:\Users\Tang\AppData\Roaming\npm\node_modules\cnpm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Users\Tang\AppData\Roaming\npm\node_modules\cnpm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:427:5)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
gyp ERR! System Windows_NT 10.0.19045
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Tang\\AppData\\Roaming\\npm\\node_modules\\cnpm\\node_modules\\npminstall\\node-gyp-bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\WINDOWS\\system32\\node_modules\\.store\\@tensorflow+tfjs-node@4.2.0\\node_modules\\@tensorflow\\tfjs-node\\lib\\napi-v8\\tfjs_binding.node" "--module_name=tfjs_binding" "--module_path=C:\\WINDOWS\\system32\\node_modules\\.store\\@tensorflow+tfjs-node@4.2.0\\node_modules\\@tensorflow\\tfjs-node\\lib\\napi-v8" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=8" "--node_napi_label=napi-v8"
gyp ERR! cwd C:\WINDOWS\system32\node_modules\.store\@tensorflow+tfjs-node@4.2.0\node_modules\@tensorflow\tfjs-node
gyp ERR! node -v v18.15.0
gyp ERR! node-gyp -v v9.3.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\WINDOWS\system32\node_modules\.store\@tensorflow+tfjs-node@4.2.0\node_modules\@tensorflow\tfjs-node\lib\napi-v8\tfjs_binding.node --module_name=tfjs_binding --module_path=C:\WINDOWS\system32\node_modules\.store\@tensorflow+tfjs-node@4.2.0\node_modules\@tensorflow\tfjs-node\lib\napi-v8 --napi_version=8 --node_abi_napi=napi --napi_build_version=8 --node_napi_label=napi-v8' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Windows\System32\node_modules\.store\@mapbox+node-pre-gyp@1.0.9\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
node-pre-gyp ERR! System Windows_NT 10.0.19045
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Windows\\System32\\node_modules\\.store\\@mapbox+node-pre-gyp@1.0.9\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\WINDOWS\system32\node_modules\.store\@tensorflow+tfjs-node@4.2.0\node_modules\@tensorflow\tfjs-node
node-pre-gyp ERR! node -v v18.15.0
node-pre-gyp ERR! node-pre-gyp -v v1.0.9
node-pre-gyp ERR! not ok

[npminstall:runscript:error] @raopics/plugin-nsfw@1.2.2 › @tensorflow/tfjs-node@^4.2.0 run install node scripts/install.js error: Error: Command failed with exit code 1: node scripts/install.js
    at makeError (C:\Users\Tang\AppData\Roaming\npm\node_modules\cnpm\node_modules\execa\lib\error.js:60:11)
    at handlePromise (C:\Users\Tang\AppData\Roaming\npm\node_modules\cnpm\node_modules\execa\index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async exports.runScript (C:\Users\Tang\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\utils.js:262:12)
    at async runLifecycleScripts (C:\Users\Tang\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\lifecycle_scripts.js:64:7)
    at async _install (C:\Users\Tang\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\install_package.js:318:5)
    at async install (C:\Users\Tang\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\install_package.js:23:12)
    at async mapper (C:\Users\Tang\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\install_package.js:270:9) {
  shortMessage: 'Command failed with exit code 1: node scripts/install.js',
  command: 'node scripts/install.js',
  escapedCommand: 'node "scripts/install.js"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
× Install fail! Error: run install error, please remove node_modules before retry!
Command failed with exit code 1: node scripts/install.js
Error: Command failed with exit code 1: node scripts/install.js
    at makeError (C:\Users\Tang\AppData\Roaming\npm\node_modules\cnpm\node_modules\execa\lib\error.js:60:11)
    at handlePromise (C:\Users\Tang\AppData\Roaming\npm\node_modules\cnpm\node_modules\execa\index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async exports.runScript (C:\Users\Tang\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\utils.js:262:12)
    at async runLifecycleScripts (C:\Users\Tang\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\lifecycle_scripts.js:64:7)
    at async _install (C:\Users\Tang\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\install_package.js:318:5)
    at async install (C:\Users\Tang\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\install_package.js:23:12)
    at async mapper (C:\Users\Tang\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\install_package.js:270:9)
npminstall version: 7.6.0
npminstall argv: C:\Program Files\nodejs\node.exe C:\Users\Tang\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\bin\install.js --fix-bug-versions --china --userconfig=C:\Users\Tang\.cnpmrc --disturl=https://cdn.npmmirror.com/binaries/node --registry=https://registry.npmmirror.com @raopics/plugin-nsfw`

**Comment by reov** [comment]
``` 
     C:\Users\Tang\.cnpmrc
      or on the command line via: npm <command> --key value
      Config info can be viewed via: npm help config
\ [0/1] Installing seedrandom@^3.0.5
> @raopics/plugin-nsfw@1.2.2 › @tensorflow/tfjs-node@4.2.0 › @tensorflow/tfjs@4.2.0 › core-js@3 postinstall C:\WINDOWS\system32\node_modules\.store\core-js@3.29.1\node_modules\core-js
| [0/1] Installing seedrandom@^3.0.5
Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js:
> https://opencollective.com/core-js
> https://patreon.com/zloirock
> https://boosty.to/zloirock
> bitcoin: bc1qlea7544qtsmj2rayg0lthvza9fau63ux0fstcz

I highly recommend reading this: https://github.com/zloirock/core-js/blob/master/docs/2023-02-14-so-whats-next.md

> @raopics/plugin-nsfw@1.2.2 › @tensorflow/tfjs-node@4.2.0 › @tensorflow/tfjs@4.2.0 › core-js@3 postinstall, finished in 109ms
> @raopics/plugin-nsfw@1.2.2 › @tensorflow/tfjs-node@^4.2.0 install C:\WINDOWS\system32\node_modules\.store\@tensorflow+tfjs-node@4.2.0\node_modules\@tensorflow\tfjs-node
- [0/1] Installing seedrandom@^3.0.5
CPU-windows-4.2.0.zip
* Downloading libtensorflow
| [0/1] Installing seedrandom@^3.0.5
- [0/1] Installing seedrandom@^3.0.5
/ [0/1] Installing seedrandom@^3.0.5
node-pre-gyp install failed with error: Error: Command failed: node-pre-gyp install --fallback-to-build
node-pre-gyp http GET https://cdn.npmmirror.com/binaries/tf-builds/pre-built-binary/napi-v8/4.2.0/CPU-windows-4.2.0.zip
node-pre-gyp ERR! install response status 404 Not Found on https://cdn.npmmirror.com/binaries/tf-builds/pre-built-binary/napi-v8/4.2.0/CPU-windows-4.2.0.zip
node-pre-gyp WARN Pre-built binaries not installable for @tensorflow/tfjs-node@4.2.0 and node@18.15.0 (node-v108 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error response status 404 Not Found on https://cdn.npmmirror.com/binaries/tf-builds/pre-built-binary/napi-v8/4.2.0/CPU-windows-4.2.0.zip
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\Tang\AppData\Roaming\npm\node_modules\cnpm\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
gyp ERR! stack     at C:\Users\Tang\AppData\Roaming\npm\node_modules\cnpm\node_modules\node-gyp\lib\find-visualstudio.js:75:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\Tang\AppData\Roaming\npm\node_modules\cnpm\node_modules\node-gyp\lib\find-visualstudio.js:369:14)
gyp ERR! stack     at C:\Users\Tang\AppData\Roaming\npm\node_modules\cnpm\node_modules\node-gyp\lib\find-visualstudio.js:71:14
gyp ERR! stack     at C:\Users\Tang\AppData\Roaming\npm\node_modules\cnpm\node_modules\node-gyp\lib\find-visualstudio.js:390:16
gyp ERR! stack     at C:\Users\Tang\AppData\Roaming\npm\node_modules\cnpm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Users\Tang\AppData\Roaming\npm\node_modules\cnpm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:427:5)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
gyp ERR! System Windows_NT 10.0.19045
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Tang\\AppData\\Roaming\\npm\\node_modules\\cnpm\\node_modules\\npminstall\\node-gyp-bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\WINDOWS\\system32\\node_modules\\.store\\@tensorflow+tfjs-node@4.2.0\\node_modules\\@tensorflow\\tfjs-node\\lib\\napi-v8\\tfjs_binding.node" "--module_name=tfjs_binding" "--module_path=C:\\WINDOWS\\system32\\node_modules\\.store\\@tensorflow+tfjs-node@4.2.0\\node_modules\\@tensorflow\\tfjs-node\\lib\\napi-v8" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=8" "--node_napi_label=napi-v8"
gyp ERR! cwd C:\WINDOWS\system32\node_modules\.store\@tensorflow+tfjs-node@4.2.0\node_modules\@tensorflow\tfjs-node
gyp ERR! node -v v18.15.0
gyp ERR! node-gyp -v v9.3.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\WINDOWS\system32\node_modules\.store\@tensorflow+tfjs-node@4.2.0\node_modules\@tensorflow\tfjs-node\lib\napi-v8\tfjs_binding.node --module_name=tfjs_binding --module_path=C:\WINDOWS\system32\node_modules\.store\@tensorflow+tfjs-node@4.2.0\node_modules\@tensorflow\tfjs-node\lib\napi-v8 --napi_version=8 --node_abi_napi=napi --napi_build_version=8 --node_napi_label=napi-v8' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Windows\System32\node_modules\.store\@mapbox+node-pre-gyp@1.0.9\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
node-pre-gyp ERR! System Windows_NT 10.0.19045
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Windows\\System32\\node_modules\\.store\\@mapbox+node-pre-gyp@1.0.9\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\WINDOWS\system32\node_modules\.store\@tensorflow+tfjs-node@4.2.0\node_modules\@tensorflow\tfjs-node
node-pre-gyp ERR! node -v v18.15.0
node-pre-gyp ERR! node-pre-gyp -v v1.0.9
node-pre-gyp ERR! not ok

[npminstall:runscript:error] @raopics/plugin-nsfw@1.2.2 › @tensorflow/tfjs-node@^4.2.0 run install node scripts/install.js error: Error: Command failed with exit code 1: node scripts/install.js
    at makeError (C:\Users\Tang\AppData\Roaming\npm\node_modules\cnpm\node_modules\execa\lib\error.js:60:11)
    at handlePromise (C:\Users\Tang\AppData\Roaming\npm\node_modules\cnpm\node_modules\execa\index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async exports.runScript (C:\Users\Tang\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\utils.js:262:12)
    at async runLifecycleScripts (C:\Users\Tang\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\lifecycle_scripts.js:64:7)
    at async _install (C:\Users\Tang\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\install_package.js:318:5)
    at async install (C:\Users\Tang\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\install_package.js:23:12)
    at async mapper (C:\Users\Tang\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\install_package.js:270:9) {
  shortMessage: 'Command failed with exit code 1: node scripts/install.js',
  command: 'node scripts/install.js',
  escapedCommand: 'node "scripts/install.js"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
× Install fail! Error: run install error, please remove node_modules before retry!
Command failed with exit code 1: node scripts/install.js
Error: Command failed with exit code 1: node scripts/install.js
    at makeError (C:\Users\Tang\AppData\Roaming\npm\node_modules\cnpm\node_modules\execa\lib\error.js:60:11)
    at handlePromise (C:\Users\Tang\AppData\Roaming\npm\node_modules\cnpm\node_modules\execa\index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async exports.runScript (C:\Users\Tang\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\utils.js:262:12)
    at async runLifecycleScripts (C:\Users\Tang\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\lifecycle_scripts.js:64:7)
    at async _install (C:\Users\Tang\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\install_package.js:318:5)
    at async install (C:\Users\Tang\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\install_package.js:23:12)
    at async mapper (C:\Users\Tang\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\install_package.js:270:9)
npminstall version: 7.6.0
npminstall argv: C:\Program Files\nodejs\node.exe C:\Users\Tang\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\bin\install.js --fix-bug-versions --china --userconfig=C:\Users\Tang\.cnpmrc --disturl=https://cdn.npmmirror.com/binaries/node --registry=https://registry.npmmirror.com @raopics/plugin-nsfw

**Comment by reov** [comment]
![image](https://user-images.githubusercontent.com/47272954/229352163-e4392bc9-0fe4-41b4-9d35-9aaf28168d11.png)

**Comment by meetqy** [comment]
<img width="1120" alt="image" src="https://user-images.githubusercontent.com/18411315/229353898-40759f7f-3e47-4c8e-84cf-61b571e11624.png">

```
cnpm i @raopics/use
```

**Comment by meetqy** [comment]
<img width="1303" alt="image" src="https://user-images.githubusercontent.com/18411315/229354026-610d702c-4c0a-4e35-9b81-39eacebd0e0c.png">

这是 library地址

<img width="1232" alt="image" src="https://user-images.githubusercontent.com/18411315/229354116-b3f769e4-8592-4925-b91a-6218e9a3001e.png">

这是API地址

访问 http://localhost:9600/r

如果能随机返回一张图片表示启动成功

**Comment by meetqy** [comment]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/18411315/229354505-bc283cde-6cb4-49a3-affe-2a1b22ae788d.png">

在rua的env里面只需要配置API的地址即可，database_url不进行开发，可以不配置

主题 和 API 是独立的2个项目

@raopics/use 是让eagle的library，可以通过API去访问
rua 仓库只是一个主题而已
